export type WordType = 'person' | 'action' | 'object';

export const majorSystemMap: { [key: string]: string[] } = {
  '0': ['s', 'z'],
  '1': ['t', 'd'],
  '2': ['n'],
  '3': ['m'],
  '4': ['r'],
  '5': ['l'],
  '6': ['j', 'ch', 'sh'],
  '7': ['k', 'g'],
  '8': ['f', 'v'],
  '9': ['p', 'b']
};

// Word lists for each type
export const wordLists: { [key in WordType]: { [key: string]: string[] } } = {
  person: {
    '00': ['Zeus', 'Seuss', 'Sissy', 'Zsa', 'Suzy', 'Zoe', 'Sasha', 'Susie', 'Zack'],
    '01': ['Sid', 'Seth', 'Saint', 'Sadie', 'Zed', 'Zita', 'Zander', 'Sage', 'Sven'],
    '02': ['Sven', 'Zane', 'Sean', 'Simon', 'Zen', 'Simone', 'Zion', 'Sunny', 'Zena'],
    '03': ['Sam', 'Seamus', 'Selma', 'Zuma', 'Sami', 'Salem', 'Samson', 'Salim'],
    '04': ['Sarah', 'Cyrus', 'Siri', 'Sarai', 'Sora', 'Soraya', 'Zara', 'Serra', 'Suri'],
    '05': ['Sal', 'Saul', 'Selena', 'Sally', 'Sol', 'Silas', 'Zola', 'Sully', 'Stella'],
    '06': ['Sachi', 'Sasha', 'Shoji', 'Shane', 'Shaw', 'Shea', 'Shay', 'Sheila', 'Shawn'],
    '07': ['Suki', 'Sagan', 'Sachs', 'Sega', 'Zeke', 'Sookie', 'Saki', 'Sky', 'Sage'],
    '08': ['Sofia', 'Steve', 'Sylvia', 'Safiya', 'Svea', 'Safi', 'Sofi', 'Seve', 'Saxon'],
    '09': ['Seb', 'Toby', 'Sape', 'Sepp', 'Saba', 'Seppe', 'Zippy', 'Spike', 'Sven'],
    '10': ['Tess', 'Dash', 'Dias', 'Taz', 'Dex', 'Dez', 'Duke', 'Dante', 'Dax'],
    '11': ['Ted', 'Todd', 'Tad', 'Dot', 'Tate', 'Didi', 'Dodi', 'Dawn', 'Dutch'],
    '12': ['Dan', 'Tina', 'Dean', 'Dane', 'Dina', 'Denny', 'Tony', 'Dana', 'Dion'],
    '13': ['Tom', 'Tim', 'Tammy', 'Tommy', 'Timmy', 'Demi', 'Tami', 'Dame', 'Duma'],
    '14': ['Tara', 'Thor', 'Terry', 'Dora', 'Troy', 'Darcy', 'Derry', 'Terra', 'Dario'],
    '15': ['Dale', 'Tal', 'Dell', 'Della', 'Telly', 'Dolly', 'Talia', 'Dylan', 'Delia'],
    '16': ['Dutch', 'Taj', 'Dash', 'Tasha', 'Dasha', 'Taji', 'Doji', 'Toji', 'Tish'],
    '17': ['Dick', 'Duke', 'Doug', 'Dirk', 'Drake', 'Dag', 'Derek', 'Diggy', 'Dodge'],
    '18': ['Dave', 'Dove', 'Duff', 'Deva', 'Taffy', 'Davy', 'Dov', 'Tavy', 'Devon'],
    '19': ['Toby', 'Deb', 'Tab', 'Tobi', 'Debby', 'Tabby', 'Doby', 'Dobby', 'Duby'],
    '20': ['Nash', 'Ness', 'Noah', 'Nils', 'Naz', 'Neo', 'Noam', 'Nessa', 'Nyx'],
    '21': ['Ned', 'Nate', 'Nat', 'Nadia', 'Nadine', 'Nita', 'Nick', 'Netta', 'Nida'],
    '22': ['Nina', 'Nan', 'Nene', 'Nino', 'Nana', 'Noni', 'Nona', 'Ninon', 'Noon'],
    '23': ['Naomi', 'Nome', 'Nim', 'Noemi', 'Nemo', 'Norm', 'Nima', 'Numa', 'Nami'],
    '24': ['Nora', 'Nero', 'Nur', 'Nuri', 'Nour', 'Nery', 'Nair', 'Noor', 'Nova'],
    '25': ['Neil', 'Noel', 'Nell', 'Nile', 'Neely', 'Nelly', 'Niall', 'Neal', 'Nola'],
    '26': ['Nige', 'Nash', 'Nish', 'Neige', 'Naj', 'Naja', 'Nijah', 'Nagi', 'Naji'],
    '27': ['Nick', 'Nik', 'Nike', 'Nico', 'Nicky', 'Nicko', 'Niko', 'Neka', 'Nack'],
    '28': ['Neve', 'Nova', 'Nev', 'Nevin', 'Novak', 'Neff', 'Niffy', 'Neave', 'Niva'],
    '29': ['Nob', 'Nap', 'Neb', 'Nabil', 'Nabby', 'Nupe', 'Nippy', 'Nubi', 'Nabe'],
    '30': ['Mace', 'Moss', 'Messi', 'Mose', 'Macy', 'Missy', 'Maisie', 'Massey', 'Max'],
    '31': ['Matt', 'Maud', 'Mitch', 'Mata', 'Mita', 'Matti', 'Maddie', 'Mitty', 'Mady'],
    '32': ['Min', 'Mann', 'Moon', 'Mina', 'Mona', 'Mooney', 'Minnie', 'Manny', 'Muni'],
    '33': ['Mimi', 'Mame', 'Mamie', 'Mae', 'Maeve', 'May', 'Mumu', 'Momo', 'Mame'],
    '34': ['Maher', 'Mir', 'Mary', 'Mira', 'Maury', 'Merry', 'Moira', 'Mara', 'Mari'],
    '35': ['Mel', 'Mal', 'Mile', 'Milo', 'Malia', 'Molly', 'Millie', 'Mali', 'Mulla'],
    '36': ['Mitch', 'Mage', 'Marsh', 'Misha', 'Masha', 'Maji', 'Miche', 'Ming', 'Mash'],
    '37': ['Mike', 'Meg', 'Mac', 'Mick', 'Maggie', 'Mickey', 'Mako', 'Mika', 'Micki'],
    '38': ['Maeve', 'Mav', 'Mavis', 'Mavie', 'Maffi', 'Miff', 'Maven', 'Mave', 'Maff'],
    '39': ['Mab', 'Moby', 'Mabe', 'Mupe', 'Mopi', 'Mabel', 'Maple', 'Mobs', 'Mack'],
    '40': ['Ross', 'Race', 'Reese', 'Russ', 'Roz', 'Rosie', 'Risa', 'Roy', 'Roxie'],
    '41': ['Rod', 'Reed', 'Rudy', 'Reid', 'Rida', 'Roth', 'Ruth', 'Rita', 'Rade'],
    '42': ['Ron', 'Rain', 'Ren', 'Rhine', 'Rowan', 'Rene', 'Ryan', 'Raina', 'Roni'],
    '43': ['Ram', 'Rome', 'Remy', 'Rahim', 'Rami', 'Romy', 'Rama', 'Roma', 'Rumi'],
    '44': ['Rory', 'Rainer', 'Ryder', 'Raoul', 'Ray', 'Roland', 'Randy', 'Roxy', 'Rio'],
    '45': ['Raul', 'Riley', 'Raleigh', 'Royal', 'Rollo', 'Rowley', 'Ryle', 'Rail', 'Rex'],
    '46': ['Raj', 'Rush', 'Rajiv', 'Reggie', 'Ridge', 'Roger', 'Roche', 'Rich', 'Raji'],
    '47': ['Rick', 'Ricky', 'Rocco', 'Rik', 'Rake', 'Rocky', 'Regan', 'Roke', 'Rako'],
    '48': ['Rafe', 'Ravi', 'Rufus', 'Rolf', 'Raff', 'Riff', 'Ralph', 'Reva', 'Rafi'],
    '49': ['Rob', 'Rip', 'Robb', 'Ruby', 'Roby', 'Robby', 'Rippy', 'Reba', 'Rabi'],
    '50': ['Lois', 'Lance', 'Liz', 'Luis', 'Lacy', 'Lacey', 'Lizzy', 'Lisa', 'Lou'],
    '51': ['Lot', 'Lloyd', 'Lad', 'Leda', 'Lydia', 'Lido', 'Lida', 'Leta', 'Lady'],
    '52': ['Lynn', 'Leon', 'Lane', 'Lenny', 'Lina', 'Lena', 'Luna', 'Loni', 'Len'],
    '53': ['Liam', 'Lem', 'Lome', 'Lemmy', 'Lumi', 'Lima', 'Loma', 'Lemy', 'Lance'],
    '54': ['Lara', 'Lori', 'Larry', 'Leroy', 'Laura', 'Lora', 'Lyre', 'Lars', 'Leo'],
    '55': ['Lyle', 'Lola', 'Lily', 'Lila', 'Lally', 'Lulu', 'Lela', 'Lali', 'Leal'],
    '56': ['Leah', 'Lech', 'Ledge', 'Leach', 'Lodge', 'Lush', 'Lage', 'Lija', 'Leigh'],
    '57': ['Luke', 'Locke', 'Lake', 'Lucky', 'Loki', 'Luka', 'Laken', 'Leck', 'Link'],
    '58': ['Leaf', 'Levi', 'Love', 'Liv', 'Liev', 'Loeve', 'Lafe', 'Liva', 'Leff'],
    '59': ['Lib', 'Lupe', 'Labe', 'Lobo', 'Lipa', 'Luba', 'Libby', 'Lenny', 'Linus'],
    '60': ['Chase', 'Jess', 'Jazz', 'Josh', 'Jace', 'Joyce', 'Josie', 'Joss', 'Jace'],
    '61': ['Jed', 'Jade', 'Jude', 'Jet', 'Jodi', 'Jada', 'Jett', 'Judd', 'Johan'],
    '62': ['Jean', 'June', 'Jin', 'Jane', 'Joan', 'John', 'Jen', 'Joni', 'Jake'],
    '63': ['Jim', 'James', 'Jamie', 'Jimmy', 'Jem', 'Jimi', 'Jules', 'Jaime', 'Jude'],
    '64': ['Jerry', 'Jeri', 'Jory', 'Jair', 'Jere', 'Jara', 'Jiro', 'Jorge', 'Jade'],
    '65': ['Joey', 'Julian', 'Jolie', 'Jill', 'Julie', 'Jolly', 'Jael', 'Juli', 'Jace'],
    '66': ['Judge', 'Joshua', 'Joshi', 'Jash', 'Jesh', 'Joy', 'Jesse', 'Jessie', 'Jade'],
    '67': ['Jack', 'Jake', 'Jacques', 'Jak', 'Jacky', 'Jackie', 'Jakes', 'Jago', 'Jedi'],
    '68': ['Jeff', 'Jove', 'Jiff', 'Java', 'Jef', 'Jovie', 'Jaffa', 'Jiva', 'Joss'],
    '69': ['Job', 'Jeb', 'Jobe', 'Jibb', 'Juba', 'Jeppe', 'Joppa', 'Jabe', 'Jubal'],
    '70': ['Case', 'Cass', 'Kess', 'Kacy', 'Kasey', 'Cassie', 'Casey', 'Kaz', 'Kay'],
    '71': ['Kate', 'Cade', 'Cody', 'Kit', 'Cato', 'Katy', 'Katie', 'Keaton', 'Kurt'],
    '72': ['Kane', 'Conn', 'Kean', 'Conan', 'Kenny', 'Connie', 'Kenna', 'Keon', 'Kenton'],
    '73': ['Cam', 'Kim', 'Kami', 'Kimi', 'Cami', 'Kimmy', 'Como', 'Kuma', 'Kemp'],
    '74': ['Kira', 'Cora', 'Carey', 'Cary', 'Kerry', 'Kori', 'Cori', 'Kari', 'Karl'],
    '75': ['Cole', 'Kyle', 'Kelly', 'Kali', 'Callie', 'Kylie', 'Keely', 'Kyla', 'Cal'],
    '76': ['Cash', 'Kage', 'Cage', 'Kesh', 'Kishi', 'Kesha', 'Kaja', 'Kash', 'Kaige'],
    '77': ['Kiki', 'Coco', 'Koko', 'Keke', 'Kirk', 'Kenny', 'Kai', 'Kendra', 'Kian'],
    '78': ['Kev', 'Cafe', 'Kiefer', 'Kovac', 'Kiva', 'Cave', 'Kavi', 'Keff', 'Knox'],
    '79': ['Kipp', 'Koby', 'Kobe', 'Kippy', 'Kappa', 'Kobi', 'Kai', 'Kitty', 'Kenji'],
    '80': ['Fitz', 'Foss', 'Felix', 'Fez', 'Faisal', 'Faris', 'Faiz', 'Faust', 'Fox'],
    '81': ['Fad', 'Fate', 'Fidel', 'Fred', 'Ford', 'Fahd', 'Faith', 'Fido', 'Fayed'],
    '82': ['Finn', 'Fawn', 'Fern', 'Fan', 'Fiona', 'Fauna', 'Fanny', 'Faun', 'Flynn'],
    '83': ['Fam', 'Femi', 'Fame', 'Foma', 'Fuma'],
    '84': ['Fair', 'Farr', 'Faro', 'Fury', 'Farah', 'Farrah', 'Fira', 'Flora', 'Fara'],
    '85': ['Fal', 'Phil', 'Fela', 'Fall', 'Flo', 'Fallon', 'Philo', 'Filiz', 'Fola'],
    '86': ['Fitch', 'Fash', 'Fish', 'Faye', 'Fiji', 'Fajr', 'Faja'],
    '87': ['Falk', 'Fike', 'Fang', 'Fargo', 'Frick'],
    '88': ['Fife', 'Faye', 'Finn', 'Fritz', 'Faith'],
    '89': ['Fab', 'Fob', 'Fib', 'flap', 'flop', 'flip'],
    '90': ['Paz', 'Pez', 'Piz', 'Posey', 'Pace', 'Pierce', 'Piers', 'Pax', 'Paz'],
    '91': ['Pat', 'Pete', 'Pitt', 'Patty', 'Peta', 'Patti'],
    '92': ['Pan', 'Penn', 'Paine', 'Pine', 'Penny', 'Pini', 'Pena'],
    '93': ['Pam', 'Palm', 'Puma', 'Paloma', 'Pema'],
    '94': ['Pierre', 'Peer', 'Pir', 'Perry', 'Paris', 'Peri', 'Para', 'Piri'],
    '95': ['Paul', 'Pell', 'Pill', 'Pearl', 'Polly', 'Pele', 'Pola'],
    '96': ['Page', 'Paige', 'Pudge', 'Peggy', 'Patch', 'Peach', 'Peja', 'Pich'],
    '97': ['Pike', 'Peck', 'Puck', 'Peggy', 'Paki', 'Paco'],
    '98': ['Pave', 'Poff', 'Puff', 'Pavey', 'Pavia'],
    '99': ['Pip', 'Pope', 'Pepe', 'Poppy']
  },
  action: {
    '00': ['seize', 'sizzle', 'suss', 'sway', 'sow', 'soar', 'shine', 'sweep', 'slide', 'sail'],
    '01': ['sort', 'send', 'sit', 'stand', 'slide', 'sift', 'stir', 'sled', 'stow', 'swing'],
    '02': ['sing', 'shine', 'sign', 'sync', 'slink', 'sneak', 'snap', 'snip', 'sway', 'swoop'],
    '03': ['swim', 'swarm', 'slam', 'swamp', 'swipe', 'swab', 'smack', 'smash', 'smile', 'smoke'],
    '04': ['soar', 'stir', 'sear', 'serve', 'stare', 'surge', 'scare', 'score', 'steer', 'store'],
    '05': ['sail', 'slide', 'seal', 'sell', 'slay', 'sling', 'slap', 'sleep', 'slip', 'slog'],
    '06': ['surge', 'switch', 'search', 'siege', 'shake', 'shift', 'shove', 'share', 'shine', 'show'],
    '07': ['seek', 'sack', 'sink', 'soak', 'skip', 'skate', 'ski', 'sock', 'suck', 'strike'],
    '08': ['serve', 'sift', 'shove', 'save', 'solve', 'sever', 'surf', 'stuff', 'sniff', 'strive'],
    '09': ['sip', 'swipe', 'swab', 'sap', 'swoop', 'sweep', 'slap', 'snap', 'stop', 'step'],
    '10': ['toss', 'doze', 'dash', 'dance', 'dive', 'daze', 'dose', 'tease', 'dice', 'dust'],
    '11': ['trade', 'dote', 'edit', 'tend', 'tide', 'tread', 'trot', 'treat', 'dread', 'doubt'],
    '12': ['train', 'turn', 'dine', 'tune', 'tan', 'tone', 'drain', 'drown', 'dawn', 'den'],
    '13': ['tame', 'time', 'dim', 'teem', 'deem', 'doom', 'dam', 'tamp', 'dump', 'damp'],
    '14': ['tear', 'draw', 'tire', 'dare', 'dry', 'drag', 'drill', 'drive', 'drape', 'drop'],
    '15': ['tell', 'dial', 'duel', 'deal', 'toil', 'till', 'toll', 'dwell', 'delay', 'dally'],
    '16': ['dodge', 'teach', 'touch', 'dash', 'ditch', 'toss', 'dust', 'test', 'taste', 'twist'],
    '17': ['talk', 'dig', 'take', 'tag', 'tug', 'tick', 'deck', 'duck', 'tack', 'dock'],
    '18': ['dive', 'drive', 'drift', 'delve', 'dive', 'defy', 'doff', 'tough', 'tuft', 'draft'],
    '19': ['dab', 'tap', 'type', 'dip', 'dupe', 'tape', 'dope', 'tip', 'top', 'dump'],
    '20': ['nose', 'nix', 'nag', 'nudge', 'nosh', 'nest', 'nap', 'nod', 'nip', 'nab'],
    '21': ['nod', 'net', 'note', 'need', 'knit', 'nest', 'negate', 'notify', 'notch', 'nix'],
    '22': ['nag', 'nix', 'name', 'numb', 'nap', 'nip', 'nab', 'neigh', 'nod', 'nap'],
    '23': ['name', 'numb', 'nip', 'nap', 'nab', 'nominate', 'numb', 'nag', 'nix', 'nod'],
    '24': ['near', 'nurse', 'nourish', 'narrate', 'nix', 'nag', 'nod', 'nap', 'nab', 'nip'],
    '25': ['nail', 'kneel', 'nullify', 'nix', 'nag', 'nod', 'nap', 'nab', 'nip', 'nod'],
    '26': ['nudge', 'nosh', 'nix', 'nag', 'nod', 'nap', 'nab', 'nip', 'nod', 'nap'],
    '27': ['knock', 'nag', 'nuke', 'nick', 'nix', 'nod', 'nap', 'nab', 'nip', 'nod'],
    '28': ['knife', 'navigate', 'nix', 'nag', 'nod', 'nap', 'nab', 'nip', 'nod', 'nap'],
    '29': ['nap', 'nip', 'nab', 'nix', 'nag', 'nod', 'nap', 'nab', 'nip', 'nod'],
    '30': ['maze', 'muse', 'miss', 'mash', 'mix', 'move', 'mend', 'mow', 'map', 'mope'],
    '31': ['mute', 'meet', 'mate', 'mend', 'mind', 'mount', 'mold', 'melt', 'mint', 'mark'],
    '32': ['mine', 'moan', 'mean', 'munch', 'mix', 'mash', 'move', 'mope', 'march', 'merge'],
    '33': ['mime', 'mum', 'moan', 'move', 'mix', 'mash', 'mend', 'meddle', 'mock', 'milk'],
    '34': ['mar', 'moor', 'merge', 'mark', 'mire', 'mourn', 'march', 'mirror', 'murmur', 'mend'],
    '35': ['mail', 'mold', 'mull', 'melt', 'milk', 'mill', 'meddle', 'mingle', 'maul', 'mend'],
    '36': ['match', 'munch', 'mesh', 'mix', 'mash', 'move', 'mend', 'mount', 'mark', 'mold'],
    '37': ['make', 'mock', 'mark', 'mingle', 'march', 'mend', 'move', 'mash', 'mount', 'mold'],
    '38': ['move', 'morph', 'miff', 'mend', 'mash', 'mingle', 'march', 'merge', 'mark', 'meet'],
    '39': ['mop', 'map', 'mob', 'mend', 'move', 'march', 'merge', 'mix', 'mash', 'mount'],
    '40': ['race', 'rise', 'roast', 'rest', 'raise', 'rinse', 'rush', 'roar', 'rouse', 'rust'],
    '41': ['raid', 'ride', 'rate', 'read', 'root', 'rid', 'rend', 'rot', 'rant', 'rout'],
    '42': ['rain', 'run', 'earn', 'reign', 'renew', 'ring', 'race', 'roar', 'rush', 'roll'],
    '43': ['roam', 'ram', 'rhyme', 'rumble', 'romp', 'ream', 'rim', 'race', 'rush', 'ride'],
    '44': ['roar', 'rear', 'race', 'rule', 'run', 'ring', 'raid', 'roll', 'rush', 'ride'],
    '45': ['roll', 'rule', 'reel', 'rail', 'relay', 'rally', 'race', 'rush', 'ride', 'roam'],
    '46': ['rage', 'rush', 'reach', 'rouse', 'ride', 'roll', 'run', 'race', 'roar', 'rule'],
    '47': ['rake', 'rock', 'rig', 'wreck', 'rack', 'rogue', 'race', 'rush', 'ride', 'roll'],
    '48': ['rave', 'reef', 'rough', 'riff', 'roof', 'race', 'rush', 'ride', 'roll', 'run'],
    '49': ['rub', 'rip', 'rap', 'rob', 'reap', 'rope', 'race', 'rush', 'ride', 'roll'],
    '50': ['laze', 'lose', 'lease', 'lace', 'loosen', 'lift', 'lean', 'laugh', 'learn', 'lead'],
    '51': ['lead', 'let', 'load', 'loot', 'light', 'laud', 'leap', 'lock', 'link', 'lure'],
    '52': ['lean', 'line', 'learn', 'loan', 'lend', 'link', 'list', 'long', 'lunge', 'last'],
    '53': ['loom', 'limp', 'leap', 'lump', 'lurk', 'lift', 'launch', 'laugh', 'live', 'love'],
    '54': ['lure', 'leer', 'lower', 'learn', 'listen', 'laugh', 'leap', 'look', 'like', 'lay'],
    '55': ['lull', 'level', 'label', 'linger', 'lean', 'lift', 'learn', 'live', 'love', 'lead'],
    '56': ['lash', 'lunge', 'launch', 'latch', 'lodge', 'laugh', 'leap', 'live', 'love', 'lead'],
    '57': ['lock', 'lag', 'lick', 'leak', 'log', 'lurk', 'lift', 'learn', 'live', 'love'],
    '58': ['live', 'love', 'laugh', 'leave', 'lift', 'lunge', 'leap', 'look', 'like', 'lay'],
    '59': ['lap', 'leap', 'lob', 'limp', 'loop', 'learn', 'live', 'love', 'lift', 'lead'],
    '60': ['chase', 'juice', 'jazz', 'jostle', 'jest', 'joist', 'chase', 'juice', 'jazz', 'jostle'],
    '61': ['jot', 'jut', 'jade', 'jilt', 'jot', 'jut', 'jade', 'jilt', 'jot', 'jut'],
    '62': ['join', 'gain', 'gin', 'join', 'gain', 'gin', 'join', 'gain', 'gin', 'join'],
    '63': ['jam', 'jump', 'jog', 'jam', 'jump', 'jog', 'jam', 'jump', 'jog', 'jam'],
    '64': ['jar', 'jeer', 'gear', 'jar', 'jeer', 'gear', 'jar', 'jeer', 'gear', 'jar'],
    '65': ['jail', 'gel', 'jell', 'jail', 'gel', 'jell', 'jail', 'gel', 'jell', 'jail'],
    '66': ['judge', 'guide', 'josh', 'judge', 'guide', 'josh', 'judge', 'guide', 'josh', 'judge'],
    '67': ['joke', 'jog', 'jag', 'joke', 'jog', 'jag', 'joke', 'jog', 'jag', 'joke'],
    '68': ['jive', 'jiff', 'give', 'jive', 'jiff', 'give', 'jive', 'jiff', 'give', 'jive'],
    '69': ['jab', 'jibe', 'jump', 'jab', 'jibe', 'jump', 'jab', 'jibe', 'jump', 'jab'],
    '70': ['case', 'kiss', 'cost', 'cast', 'cease', 'cause', 'case', 'kiss', 'cost', 'cast'],
    '71': ['cut', 'code', 'coat', 'cite', 'catch', 'quote', 'cut', 'code', 'coat', 'cite'],
    '72': ['can', 'coin', 'cane', 'con', 'keen', 'coon', 'can', 'coin', 'cane', 'con'],
    '73': ['come', 'comb', 'calm', 'come', 'comb', 'calm', 'come', 'comb', 'calm', 'come'],
    '74': ['care', 'cure', 'core', 'care', 'cure', 'core', 'care', 'cure', 'core', 'care'],
    '75': ['call', 'cool', 'coil', 'call', 'cool', 'coil', 'call', 'cool', 'coil', 'call'],
    '76': ['cash', 'cage', 'catch', 'cash', 'cage', 'catch', 'cash', 'cage', 'catch', 'cash'],
    '77': ['cook', 'kick', 'cake', 'cook', 'kick', 'cake', 'cook', 'kick', 'cake', 'cook'],
    '78': ['cave', 'cuff', 'cough', 'cave', 'cuff', 'cough', 'cave', 'cuff', 'cough', 'cave'],
    '79': ['cap', 'cope', 'cup', 'cap', 'cope', 'cup', 'cap', 'cope', 'cup', 'cap'],
    '80': ['face', 'fuse', 'faze', 'focus', 'fizz', 'fess', 'foist', 'feast', 'force', 'freeze'],
    '81': ['fade', 'feed', 'fit', 'fight', 'fete', 'fend', 'float', 'flaunt', 'flirt', 'fret'],
    '82': ['fan', 'feign', 'fawn', 'fasten', 'fling', 'fence', 'finish', 'find', 'fine', 'faint'],
    '83': ['foam', 'frame', 'form', 'flame', 'film', 'farm', 'firm', 'fume'],
    '84': ['fire', 'fare', 'fear', 'flare', 'forge', 'free', 'fry', 'fair', 'fur', 'floor'],
    '85': ['fail', 'fall', 'feel', 'fill', 'file', 'foil', 'fool', 'furl', 'frill', 'flail'],
    '86': ['fetch', 'fish', 'flush', 'flash', 'finish', 'forge', 'fudge', 'fuse', 'fash', 'fresh'],
    '87': ['fake', 'fog', 'flog', 'frag', 'fling', 'flag', 'fang', 'frog', 'fig', 'fug'],
    '88': ['fife', 'fave', 'fluff', 'float', 'fade'],
    '89': ['fab', 'fob', 'fib', 'flap', 'flop', 'flip'],
    '90': ['pass', 'pause', 'piece', 'poise', 'pace', 'push', 'press', 'pose', 'prize', 'please'],
    '91': ['pat', 'pet', 'pit', 'pout', 'paint', 'point', 'pelt', 'plant', 'print', 'post'],
    '92': ['pin', 'pan', 'pawn', 'pen', 'pine', 'preen', 'prune', 'plan', 'pun', 'pone'],
    '93': ['pump', 'pimp', 'plump', 'plumb', 'palm', 'plume', 'prime', 'pram', 'pom', 'puma'],
    '94': ['pear', 'pier', 'poor', 'pair', 'pore', 'pure', 'pyre', 'pour', 'par'],
    '95': ['pole', 'pile', 'pill', 'pool', 'pail', 'peel', 'poll', 'pall', 'pearl'],
    '96': ['page', 'push', 'punch', 'poach', 'patch', 'pinch', 'parch', 'perch', 'pitch', 'posh'],
    '97': ['pike', 'peak', 'puck', 'pack', 'poke', 'pick', 'peck', 'park', 'pork', 'punk'],
    '98': ['puff', 'pave', 'proof', 'poof', 'push', 'pull'],
    '99': ['pipe', 'pop', 'pup', 'pope', 'pump', 'pip', 'pap', 'peep', 'poop', 'pulp']
  },
  object: {
    '00': ['sauce', 'swiss', 'suds', 'sash', 'saucer', 'sushi', 'soap', 'silk', 'spice', 'sage'],
    '01': ['seed', 'suit', 'site', 'saddle', 'soda', 'sword', 'sedan', 'satin', 'soot', 'stud'],
    '02': ['stone', 'sign', 'sun', 'sand', 'snow', 'sink', 'snake', 'snack', 'song', 'swan'],
    '03': ['steam', 'sum', 'psalm', 'swamp', 'stem', 'seam', 'swarm', 'silk', 'soap', 'sack'],
    '04': ['sewer', 'store', 'star', 'scar', 'spur', 'spear', 'stair', 'sore', 'spar', 'straw'],
    '05': ['seal', 'soil', 'sole', 'sail', 'sill', 'slaw', 'sled', 'spool', 'slab', 'slat'],
    '06': ['stage', 'sash', 'siege', 'switch', 'shoe', 'shack', 'shell', 'ship', 'shop', 'shed'],
    '07': ['sock', 'sack', 'sake', 'sky', 'ski', 'scale', 'skate', 'silk', 'sink', 'sword'],
    '08': ['safe', 'surf', 'sphere', 'sofa', 'scarf', 'staff', 'shelf', 'skiff', 'scuff', 'stone'],
    '09': ['soap', 'soup', 'sap', 'sip', 'spool', 'spade', 'spoon', 'sponge', 'spa', 'spine'],
    '10': ['dice', 'dust', 'dose', 'disk', 'desk', 'dish', 'dais', 'dice', 'disc', 'dash'],
    '11': ['dot', 'date', 'debt', 'dart', 'dent', 'dirt', 'dart', 'ditch', 'dust', 'diet'],
    '12': ['den', 'dune', 'dawn', 'tin', 'town', 'tuna', 'ton', 'tank', 'tune', 'tent'],
    '13': ['dome', 'dime', 'dam', 'drum', 'tomb', 'tram', 'team', 'dome', 'dime', 'dam'],
    '14': ['door', 'deer', 'tire', 'tower', 'tar', 'tray', 'tree', 'drawer', 'drill', 'drain'],
    '15': ['doll', 'deal', 'dial', 'tile', 'tail', 'tool', 'towel', 'tile', 'doll', 'dell'],
    '16': ['dish', 'torch', 'ditch', 'dash', 'torch', 'tissue', 'dough', 'dish', 'torch', 'dash'],
    '17': ['dock', 'deck', 'dog', 'tank', 'truck', 'tag', 'tack', 'dock', 'deck', 'duck'],
    '18': ['dove', 'dive', 'duff', 'tube', 'tiff', 'turf', 'tuff', 'dove', 'dive', 'duff'],
    '19': ['tape', 'tub', 'dupe', 'tap', 'tube', 'tip', 'top', 'tape', 'tub', 'tip'],
    '20': ['nose', 'nest', 'nuts', 'noose', 'news', 'niece', 'nails', 'net', 'nozzle', 'nachos'],
    '21': ['net', 'node', 'note', 'needle', 'noodle', 'nut', 'notebook', 'nectarine', 'nit', 'nest'],
    '22': ['nun', 'neon', 'nine', 'naan', 'noon', 'nylon', 'neon', 'neuron', 'nanny', 'nine'],
    '23': ['name', 'gnome', 'nail', 'numb', 'nap', 'nib', 'net', 'nut', 'node', 'nap'],
    '24': ['nerve', 'noir', 'net', 'narwhal', 'nori', 'nurse', 'nerd', 'north', 'nori', 'noir'],
    '25': ['nail', 'knoll', 'nut', 'needle', 'noodle', 'nozzle', 'nickel', 'nail', 'knoll', 'null'],
    '26': ['niche', 'notch', 'nash', 'niche', 'notch', 'nash', 'niche', 'notch', 'nash', 'niche'],
    '27': ['neck', 'nook', 'nag', 'nickel', 'nook', 'nag', 'neck', 'nook', 'nag', 'neck'],
    '28': ['knife', 'nave', 'neph', 'knife', 'nave', 'neph', 'knife', 'nave', 'neph', 'knife'],
    '29': ['nib', 'knob', 'nape', 'nib', 'knob', 'nape', 'nib', 'knob', 'nape', 'nib'],
    '30': ['maze', 'moss', 'mist', 'mouse', 'moose', 'mask', 'mat', 'mitt', 'mast', 'mist'],
    '31': ['mat', 'meat', 'mitt', 'mast', 'mist', 'mint', 'mat', 'meat', 'mitt', 'mast'],
    '32': ['moon', 'mane', 'mine', 'money', 'menu', 'mint', 'mane', 'moon', 'mine', 'money'],
    '33': ['meme', 'mum', 'mime', 'mummy', 'memo', 'meme', 'mum', 'mime', 'mummy', 'memo'],
    '34': ['mare', 'mire', 'moor', 'mirror', 'marker', 'marble', 'mortar', 'mare', 'mire', 'moor'],
    '35': ['mall', 'meal', 'mile', 'mallet', 'mule', 'mill', 'mole', 'mall', 'meal', 'mile'],
    '36': ['match', 'mesh', 'marsh', 'machine', 'mush', 'mesh', 'match', 'marsh', 'mash', 'mesh'],
    '37': ['mask', 'mug', 'make', 'mic', 'muck', 'mug', 'mask', 'make', 'mic', 'muck'],
    '38': ['movie', 'myth', 'muff', 'movie', 'myth', 'muff', 'movie', 'myth', 'muff', 'movie'],
    '39': ['map', 'mop', 'mob', 'map', 'mop', 'mob', 'map', 'mop', 'mob', 'map'],
    '40': ['rose', 'rice', 'race', 'roast', 'rust', 'resin', 'rose', 'rice', 'race', 'roast'],
    '41': ['rod', 'road', 'root', 'reed', 'rat', 'rite', 'rod', 'road', 'root', 'reed'],
    '42': ['rain', 'rune', 'iron', 'rain', 'rune', 'iron', 'rain', 'rune', 'iron', 'rain'],
    '43': ['room', 'ram', 'rim', 'room', 'ram', 'rim', 'room', 'ram', 'rim', 'room'],
    '44': ['rare', 'roar', 'rear', 'race', 'roar', 'rear', 'race', 'roar', 'rear', 'race'],
    '45': ['rail', 'roll', 'reel', 'rail', 'roll', 'reel', 'rail', 'roll', 'reel', 'rail'],
    '46': ['ridge', 'rush', 'rouge', 'ridge', 'rush', 'rouge', 'ridge', 'rush', 'rouge', 'ridge'],
    '47': ['rock', 'rag', 'rake', 'rock', 'rag', 'rake', 'rock', 'rag', 'rake', 'rock'],
    '48': ['reef', 'raft', 'riff', 'roof', 'rail', 'ring', 'rack', 'rock', 'rug', 'rod'],
    '49': ['rope', 'robe', 'rip', 'rib', 'ruby', 'rim', 'ramp', 'rag', 'rack', 'rod'],
    '50': ['lens', 'leaf', 'list', 'lamp', 'lock', 'lake', 'line', 'lace', 'log', 'lid'],
    '51': ['lot', 'light', 'land', 'link', 'loop', 'lane', 'loft', 'lute', 'loot', 'lint'],
    '52': ['line', 'loan', 'lane', 'lens', 'lock', 'link', 'list', 'lamp', 'log', 'lid'],
    '53': ['lime', 'lamb', 'loom', 'lamp', 'leaf', 'lens', 'lake', 'log', 'lid', 'lock'],
    '54': ['lure', 'lyre', 'lair', 'lamp', 'lens', 'lake', 'log', 'lid', 'lock', 'link'],
    '55': ['lily', 'leaf', 'lamp', 'lens', 'lake', 'log', 'lid', 'lock', 'link', 'list'],
    '56': ['leash', 'lash', 'ledge', 'lamp', 'lens', 'lake', 'log', 'lid', 'lock', 'link'],
    '57': ['lake', 'log', 'lock', 'lamp', 'lens', 'leaf', 'lid', 'link', 'list', 'lane'],
    '58': ['leaf', 'loaf', 'lamp', 'lens', 'lake', 'log', 'lid', 'lock', 'link', 'list'],
    '59': ['lip', 'lab', 'lamp', 'lens', 'lake', 'log', 'lid', 'lock', 'link', 'list'],
    '60': ['juice', 'chess', 'jazz', 'jade', 'jar', 'jeans', 'jet', 'jam', 'jewel', 'joint'],
    '61': ['jet', 'jade', 'jute', 'jam', 'joint', 'jug', 'jar', 'jeep', 'jail', 'jolt'],
    '62': ['gin', 'jean', 'june', 'gem', 'jar', 'jug', 'jet', 'jam', 'jewel', 'joint'],
    '63': ['gem', 'jam', 'gym', 'game', 'gum', 'gown', 'gate', 'gear', 'gun', 'globe'],
    '64': ['gear', 'gore', 'gyre', 'grill', 'grate', 'grape', 'grid', 'graph', 'grove', 'grain'],
    '65': ['goal', 'gill', 'gull', 'gale', 'gold', 'gulf', 'glow', 'globe', 'grill', 'glass'],
    '66': ['gauge', 'gash', 'gouge', 'gem', 'gown', 'gate', 'grid', 'grove', 'gulf', 'glass'],
    '67': ['gig', 'gag', 'game', 'gear', 'gun', 'globe', 'grill', 'grain', 'grate', 'grape'],
    '68': ['gift', 'guff', 'gaff', 'gulf', 'glow', 'gold', 'gill', 'gull', 'gale', 'goal'],
    '69': ['gap', 'gob', 'gape', 'group', 'grip', 'graph', 'guild', 'guard', 'gown', 'gate'],
    '70': ['case', 'kiss', 'quiz', 'cage', 'cross', 'coast', 'crest', 'course', 'cast', 'cost'],
    '71': ['cat', 'kite', 'code', 'cart', 'cot', 'coat', 'card', 'cord', 'crate', 'court'],
    '72': ['coin', 'cone', 'cane', 'crown', 'chain', 'corn', 'can', 'crib', 'crane', 'clan'],
    '73': ['comb', 'camp', 'clam', 'cram', 'cream', 'chrome', 'crime', 'crumb', 'claim', 'comb'],
    '74': ['car', 'core', 'cure', 'crow', 'crier', 'choir', 'care', 'carp', 'crust', 'crate'],
    '75': ['coal', 'call', 'coil', 'claw', 'cell', 'cull', 'curl', 'calf', 'cliff', 'club'],
    '76': ['cage', 'cash', 'coach', 'church', 'cheese', 'chalk', 'chain', 'chest', 'chair', 'chief'],
    '77': ['cake', 'cog', 'cook', 'clock', 'coke', 'cork', 'creek', 'crack', 'crock', 'cloak'],
    '78': ['cave', 'cuff', 'cove', 'cliff', 'calf', 'chief', 'cafe', 'cuff', 'cove', 'curve'],
    '79': ['cap', 'cob', 'cube', 'cup', 'cape', 'cope', 'coop', 'cop', 'carp', 'camp'],
    '80': ['face', 'fez', 'fuse', 'fox', 'fist', 'feast', 'fence', 'flask', 'floss', 'force'],
    '81': ['foot', 'food', 'fat', 'fort', 'fate', 'field', 'fruit', 'flute', 'fist', 'fund'],
    '82': ['fan', 'fin', 'fawn', 'fern', 'phone', 'fence', 'flint', 'fund', 'fang', 'font'],
    '83': ['foam', 'frame', 'form', 'flame', 'film', 'farm', 'firm', 'fume'],
    '84': ['fire', 'fur', 'fair', 'fear', 'floor', 'fir', 'flare', 'flour', 'fern', 'frill'],
    '85': ['file', 'foil', 'fall', 'fowl', 'fuel', 'foal', 'fool', 'fill', 'fell', 'flail'],
    '86': ['fish', 'flesh', 'flash', 'fudge', 'fog', 'forge', 'fridge', 'fang', 'fig', 'frog'],
    '87': ['flag', 'frog', 'fig', 'fog', 'fang', 'fug', 'fag', 'flog', 'frag', 'fug'],
    '88': ['fife', 'fluff', 'float', 'flask', 'flint'],
    '89': ['fob', 'fab', 'fib', 'flap', 'flop', 'flip'],
    '90': ['peas', 'peace', 'pass', 'piece', 'pose', 'pause', 'paste', 'prize', 'pulse', 'poise'],
    '91': ['pot', 'pit', 'pet', 'peat', 'pint', 'paint', 'point', 'path', 'port', 'post'],
    '92': ['pan', 'pin', 'pen', 'pine', 'pawn', 'pane', 'pond', 'pain', 'pun', 'peon'],
    '93': ['palm', 'pump', 'plum', 'poem', 'prism', 'plume', 'prime', 'pram', 'pom', 'puma'],
    '94': ['pear', 'pier', 'poor', 'pair', 'pore', 'pure', 'pyre', 'pour', 'par'],
    '95': ['pole', 'pile', 'pill', 'pool', 'pail', 'peel', 'poll', 'pall', 'pearl'],
    '96': ['page', 'pouch', 'patch', 'peach', 'pooch', 'porch', 'perch', 'pinch', 'pitch', 'posh'],
    '97': ['pike', 'peak', 'puck', 'pack', 'poke', 'pick', 'peck', 'park', 'pork', 'punk'],
    '98': ['puff', 'pave', 'proof', 'poof', 'plume'],
    '99': ['pipe', 'pop', 'pup', 'pope', 'pump', 'pip', 'pap', 'peep', 'poop', 'pulp']
  }
}; 